version: '3.8'

services:
  transcoder:
    build: .
    ports:
      - "8080:8080"
    environment:
      # S3-Compatible Storage
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION:-us-east-1}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_RESULT_BUCKET_NAME=${S3_RESULT_BUCKET_NAME}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
      
      # Authentication
      - JWT_SECRET=${JWT_SECRET}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-${JWT_SECRET}}
    
    volumes:
      # Optional: Mount temp directory for better performance
      - /tmp:/tmp
    
    restart: unless-stopped
    
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G
    
    # Note: Token is printed to logs on startup
    # View with: docker-compose logs transcoder | grep "Authentication Token" -A 5

